# Generated by Django 3.0.4 on 2021-01-22 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('Calculus', models.PositiveIntegerField(null=True)),
                ('DataBase', models.PositiveIntegerField(null=True)),
                ('LinerAlgebra', models.PositiveIntegerField(null=True)),
                ('intro_to_CS', models.PositiveIntegerField(null=True)),
                ('Intro_to_IS', models.PositiveIntegerField(null=True)),
                ('Discrete_Math', models.PositiveIntegerField(null=True)),
                ('ObjectOriented', models.PositiveIntegerField(null=True)),
                ('Statistics', models.PositiveIntegerField(null=True)),
                ('ProgramingLanguage', models.PositiveIntegerField(null=True)),
                ('DifferentialEquation', models.PositiveIntegerField(null=True)),
                ('DataStructure', models.PositiveIntegerField(null=True)),
                ('FileProcessing', models.PositiveIntegerField(null=True)),
                ('AdvancedMathematics', models.PositiveIntegerField(null=True)),
                ('Physics', models.PositiveIntegerField(null=True)),
                ('Stochastic', models.PositiveIntegerField(null=True)),
                ('Multimedia', models.PositiveIntegerField(null=True)),
                ('InformationTheory', models.PositiveIntegerField(null=True)),
                ('SystemAnalysis_And_Design', models.PositiveIntegerField(null=True)),
                ('Department', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
