# Generated by Django 3.1.4 on 2021-01-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='intro_to_CS',
            new_name='Intro_to_CS',
        ),
    ]
