# Generated by Django 3.1.4 on 2021-01-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_auto_20210122_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
