# Generated by Django 3.1.4 on 2021-01-23 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Model', '0003_auto_20210122_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
        migrations.AddField(
            model_name='student',
            name='Department_DS',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Department_SVM',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Department_WE',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
