# Generated by Django 3.1.4 on 2021-01-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_auto_20210124_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Operations_Researsh',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department_DS',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department_SVM',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department_WE',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
